kind: Service
apiVersion: v1
metadata:
  name: sribalajikumaran
  labels:
    app: sribalajikumaran
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: sribalajikumaran
  type: LoadBalancer

